### ISSUE TITLE
FutureWarning: arrays to stack must be passed as a "sequence" type

### ISSUE THREAD

**Issue by aaquijef** [digicatapult/fornax#24]
Hi all,

Whenever I run the following:
with fornax.Connection('sqlite:///mydb.sqlite') as conn:
    results = query.execute(n=5)

I get:
FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  stacked = np.vstack(v for v in keys)
Traceback (most recent call last):
  File "C:\Users\amart\OneDrive\Documents\Missing Link Music\Graph Matching Project\NodesEdg_v4.py", line 190, in <module>
    results = query.execute(n=5)
  File "C:\Users\amart\Anaconda3\lib\site-packages\fornax\api.py", line 967, in execute
    packed = self._optimise(hopping_distance, max_iters, offsets)
  File "C:\Users\amart\Anaconda3\lib\site-packages\fornax\api.py", line 881, in _optimise
    max_iters=max_iters
  File "C:\Users\amart\Anaconda3\lib\site-packages\fornax\opt.py", line 709, in solve
    refine(tuple(seed), subgraph_match)
  File "C:\Users\amart\Anaconda3\lib\site-packages\fornax\opt.py", line 486, in __call__
    self(neighbour, result)
  File "C:\Users\amart\Anaconda3\lib\site-packages\fornax\opt.py", line 485, in __call__
    for neighbour in self.neighbours[seed]:
KeyError: (0, 9057)
[Finished in 23.5s]

I have no idea where the iterator is so I can change it to a list. The weird thing is yesterday I ran all the code normally and even the graph matching matplotlib image showed up for a specific query; with some other queries resulting into this error. However, after fixing the edges dataset, all my queries resulted into this error.

Thanks in advance!

**Comment by Dan-Staff** [comment]
Hi, I've submitted a pull request to remove the future warning being raised by np.vstack.

Regarding the KeyError: I'm happy to try and look into this but I'd need a small example that shows how to recreate the bug.

Can you share a small example that will recreate this error?
Can you elaborate on what you mean by "fixed the edges dataset"?

**Comment by aaquijef** [comment]
Hi Daniel,

Very happy to have heard from one of the creators of this algorithm. Let me
just start by thanking you for providing such a fantastic tool to those of
us who care about implementing new inventions to make data preparation
dramatically easier. My teammates had no clue that there would be
alternative solutions to spending four full days of work for four people
(so technically, sixteen days) manually selecting the right Writer Name or
Publisher Name. Some of them even resist the idea of letting Machine
Learning replace the old technologies that have been in place since the
1990s.

I no longer have issues with this initial problem I described. Rather, if
there is any chance you could offer your help in solving the following that
would be helpful.
To give you better context, I changed the hopping_distance to equal 1 and
the QueryHandle _get_scores class method by adding len(query_scores) to the
score instead of sz (both of these changes within api.py). In addition, I
used the fuzz.token_set_ratio function from the fuzzywuzzy library to
obtain a better node_scoring_function.

   1. If I make a query such as "x-men", "carol danvers", "captain marvel",
   I will get one of the top results matching "x-men" with a target field that
   does not share the same superhero team type. In other words, it would match
   something like "Ms. Marvel" (an alias) or even "Carol Danvers".
   2. Why are scores not lower when one of the target fields does not match
   the respective query field at all? The Ms. Marvel example above gives me a
   0.90 similarity score.

I also added you on LinkedIn for more direct communication.

Regards,
Andre Aquije-Flores

**Comment by Dan-Staff** [comment]
Hi Andre,

Thanks for your interest in the project. It's great that others have found it useful. It's very hard to answer your question without seeing exactly what you've done. If you could share a short code snippet here with your changes to `_get_scores` then I'll do my best to get back to you. Alternatively fork the repo and share your changes on a branch there. 

Dan

**Comment by aaquijef** [comment]
Hi Dan,

Of course.
[image: image.png]

But like I said before I made two other important changes, just so that we
are on the same page.

Regards,
Martin Aquije

**Comment by hassan-digicatapult** [comment]
@aaquijef Since the original problem has been resolved I am closing this issue. I am assuming the discussion has moved to a forked version of this repo.

**Comment by aaquijef** [comment]
Hi,

Would love to still hear from Daniel though about my other problem as he
kindly offered his help.
Also, is there any way to completely erase the issue that has been posted?
I had no idea our email conversation would be publicly available on the web
for viewing. Would appreciate your support in getting rid of it.

Thank you,
Martin Aquije

**Comment by hassan-digicatapult** [comment]
@aaquijef I can remove the text of the comments you made via email - but I will keep the stub of the message so that we can track this properly. Can you please get in touch with Dan directly about the problem you have and discuss how you want to resolve it (whether via a fork, in this repo or some other mean. I believe Dan's email address is publicly available on his profile.

**Comment by hmahmud42** [comment]
test

**Comment by aaquijef** [comment]
Hi Hassan,

Dan's email address did not actually appear in his Github profile. If you
can help me get that I'd really appreciate it.
I just wanted to ask a question that you may be able to respond... Why is
the mechanism labeled as Artificial Intelligence? Just trying to understand
where the AI component in the tool is represented.

Here is a link for reference.
https://medium.com/blokur/match-that-consolidating-musical-works-registrations-with-graph-matching-d0e7bfe47303

Regards,
Martín Aquije

**Comment by hassan-digicatapult** [comment]
Hi Martin,

This repo is not tagged as AI but data-science (and some related tags). AI is just one component of DS - data analysis is a big part of it, and this is where this repo fits in (for searching over graphs).

However, I imagine you can use the tools here to construct a kernel function for [kernel methods](https://en.wikipedia.org/wiki/Kernel_method) - or other similarity based machine learning methods.

Let me know if this helps.

Best,
-Hassan.

**Comment by Dan-Staff** [comment]
Hello Martín,

Like Hassan says this repo doesn't make any claims to being a Machine Learning or Artificial Intelligence library. If other people have used it in this context then you will have to ask them about it.

Dan

**Comment by aaquijef** [comment]
Hi Hassan and Daniel,

But could it not be argued that it falls under Reactive AI given that
despite the mechanism not being able to learn, it's able to find the
optimal solution to a posed problem based on field relationships?

Regards,
Martin

**Comment by aaquijef** [comment]
In any case, I'd really appreciate understanding how the repo ties into
Data Science.
